### ISSUE TITLE
【Fix】Webpackerのエラーを消し、スタイルを変更を反映できるようにする

### ISSUE THREAD

**Issue by fujjima** [fujjima/fujjima-blog#101]
## What

webpackerのコンパイル時に以下のようなエラーが表示されるので修正して、コンパイルできるようにする

```
[Webpacker] Compiling...
[Webpacker] Compilation failed:
Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-property-in-object since the "loose" mode option was set to "true" for @babel/plugin-proposal-class-properties.
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
        ["@babel/plugin-proposal-private-property-in-object", { "loose": true }]
to the "plugins" section of your Babel config.
Though the "loose" option was set to "false" in your @babel/preset-env config, it will not be used for @babel/plugin-proposal-private-methods since the "loose" mode option was set to "true" for @babel/plugin-proposal-private-property-in-object.
The "loose" option must be the same for @babel/plugin-proposal-class-properties, @babel/plugin-proposal-private-methods and @babel/plugin-proposal-private-property-in-object (when they are enabled): you can silence this warning by explicitly adding
        ["@babel/plugin-proposal-private-methods", { "loose": true }]
to the "plugins" section of your Babel config.
node:internal/crypto/hash:69
  this[kHandle] = new _Hash(algorithm, xofLen);
```

## 参考

`https://github.com/rails/webpacker/issues/3008`

**Comment by fujjima** [comment]
「参考」を参考に修正したら、以下のようなエラーが表示された。
```
[Webpacker] Compiling...
[Webpacker] Compilation failed:
node:internal/crypto/hash:69
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/katsui/Ruby/workspace/fujjima_blog/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/katsui/Ruby/workspace/fujjima_blog/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/katsui/Ruby/workspace/fujjima_blog/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/katsui/Ruby/workspace/fujjima_blog/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/katsui/Ruby/workspace/fujjima_blog/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/katsui/Ruby/workspace/fujjima_blog/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/katsui/Ruby/workspace/fujjima_blog/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/Users/katsui/Ruby/workspace/fujjima_blog/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /Users/katsui/Ruby/workspace/fujjima_blog/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/Users/katsui/Ruby/workspace/fujjima_blog/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /Users/katsui/Ruby/workspace/fujjima_blog/node_modules/babel-loader/lib/index.js:59:71 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

webpacker5系にしたら直るようだが、そもそもwebpackerはその内廃止するので、先にruby, rails, webpackの更新をした方がいいかもしれない。

**Comment by fujjima** [comment]
一旦webpackerを5系にしてみる

**Comment by fujjima** [comment]
ruby,railsのアップデート完了。
webpackerではなく、Shakapackerに置き換える方向性を検討してみる。
https://github.com/shakacode/shakapacker
